<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11105" started-at="2020-05-13T17:18:50 IST" finished-at="2020-05-13T17:19:01 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11105" started-at="2020-05-13T17:18:50 IST" finished-at="2020-05-13T17:19:01 IST">
      <class name="com.aptence.qa.testcases.SignUpPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.aptence.qa.testcases.SignUpPageTest@394e1a0f]" name="setUp" is-config="true" duration-ms="9139" started-at="2020-05-13T17:18:50 IST" finished-at="2020-05-13T17:18:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifySignUpTest()[pri:0, instance:com.aptence.qa.testcases.SignUpPageTest@394e1a0f]" name="verifySignUpTest" duration-ms="1224" started-at="2020-05-13T17:18:59 IST" finished-at="2020-05-13T17:19:00 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.aptence.qa.pages.SignUpPage.verifyRegisteration(SignUpPage.java:54)
at com.aptence.qa.testcases.SignUpPageTest.verifySignUpTest(SignUpPageTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySignUpTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.aptence.qa.testcases.SignUpPageTest@394e1a0f]" name="tearDown" is-config="true" duration-ms="684" started-at="2020-05-13T17:19:00 IST" finished-at="2020-05-13T17:19:01 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.aptence.qa.testcases.SignUpPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
